const level1 = new Level(
    [
        new PufferFish(),
        new PufferFish(),
        new PufferFish(),
        new PufferFish(),
        new PufferFish(),
        new JellyFish(),
        new JellyFish(),
        new JellyFish(),
        new JellyFish(),
        new JellyFish(),
        new JellyFish(),
        new JellyFish(),
        new ElectroJelly(1500),
        new ElectroJelly(1600),
        new ElectroJelly(1700),
    ],
    [
        new Floor('./img/3. Background/Layers/2. Floor/L2.png', -1024),
        new Floor('./img/3. Background/Layers/2. Floor/L1.png', 0),
        new Floor('./img/3. Background/Layers/2. Floor/L2.png', 1024),
        new Floor('./img/3. Background/Layers/2. Floor/L1.png', 2048),
    ],
)